{
 "title": "Sensu Benchmarks (>= 6.4.0)",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "job",
    "query": "label_values(node_exporter_build_info, job)"
   },
   {
    "name": "node",
    "label": "Host:",
    "query": "label_values(node_exporter_build_info{job=~\"$job\"}, instance)"
   },
   {
    "name": "port",
    "label": "Port",
    "query": "label_values(node_exporter_build_info{instance=~\"$node:(.*)\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Backend Heap Bytes Allocated",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(go_memstats_alloc_bytes{job=\"etcd\"}) by (instance)"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(go_goroutines{job=\"etcd\"}) by (instance)"
    }
   ]
  },
  {
   "title": "GC Duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(go_gc_duration_seconds{job=\"etcd\"}) by (instance)"
    }
   ]
  },
  {
   "title": "GC Percent of CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    { "expr": "go_memstats_gc_cpu_fraction" }
   ]
  },
  { "title": "Sensu", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Threads",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(go_threads) by (instance)" }
   ]
  },
  {
   "title": "Busy Event Handlers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sensu_go_event_handlers_busy" }
   ]
  },
  {
   "title": "Event Throughput (All Backends)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(sensu_go_agentd_event_bytes_sum{type=\"check\"}[1m]))",
     "legendFormat": "agentd events (check)"
    },
    {
     "expr": "sum(rate(sensu_go_agentd_event_bytes_sum{type=\"metrics\"}[1m]))",
     "legendFormat": "agentd events (metric)"
    },
    {
     "expr": "sum(rate(sensu_go_agentd_event_bytes_sum{type=\"check+metrics\"}[1m]))",
     "legendFormat": "agent events (check+metric)"
    },
    {
     "expr": "sum(rate(sensu_go_store_event_bytes_sum{type=\"check\"}[1m]))",
     "legendFormat": "store events (check)"
    },
    {
     "expr": "sum(rate(sensu_go_store_event_bytes_sum{type=\"check+metric\"}[1m]))",
     "legendFormat": "store events (check+metric)"
    },
    {
     "expr": "sum(rate(sensu_go_agentd_event_bytes_sum[1m]))",
     "legendFormat": "agentd events (total)"
    },
    {
     "expr": "sum(rate(sensu_go_store_event_bytes_sum[1m]))",
     "legendFormat": "store events (total)"
    }
   ]
  },
  {
   "title": "Event Throughput (Per Backend)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(sensu_go_agentd_event_bytes_sum[1m])"
    },
    {
     "expr": "rate(sensu_go_store_event_bytes_sum[1m])"
    }
   ]
  },
  {
   "title": "Event Size Distribution",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "sensu_go_agentd_event_bytes" }
   ]
  },
  {
   "title": "Keepalive Checkins",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(sensu_go_keepalives{status=\"alive\"}[1m]))"
    },
    {
     "expr": "sum(rate(sensu_go_keepalives{status=\"dead\"}[1m]))"
    }
   ]
  },
  {
   "title": "Event Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sensu_go_event_handler_duration"
    }
   ]
  },
  {
   "title": "Total processed events per second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(sensu_go_events_processed[1m]))",
     "legendFormat": "1 min average"
    },
    {
     "expr": "sum(rate(sensu_go_events_processed[5m]))",
     "legendFormat": "5 min average"
    }
   ]
  },
  {
   "title": "Processed events per second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(sensu_go_events_processed{status=\"success\"}[1m])) by (instance)"
    },
    {
     "expr": "sum(rate(sensu_go_events_processed{status=\"failure\"}[1m])) by (instance)"
    }
   ]
  },
  {
   "title": "Agent sessions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sensu_go_agent_sessions" }
   ]
  },
  {
   "title": "Etcd operations per second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(rate(etcd_mvcc_delete_total[1m]))",
     "legendFormat": "Number of deletes seen"
    },
    {
     "expr": "avg(rate(etcd_mvcc_put_total[1m]))",
     "legendFormat": "Number of puts seen"
    },
    {
     "expr": "avg(rate(etcd_mvcc_range_total[1m]))",
     "legendFormat": "Number of ranges seen"
    },
    {
     "expr": "avg(rate(etcd_mvcc_txn_total[1m]))",
     "legendFormat": "Number of txns seen"
    }
   ]
  },
  {
   "title": "Etcd total number of keys",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "etcd_debugging_mvcc_keys_total", "legendFormat": "Count" }
   ]
  },
  {
   "title": "Etcd Disk Sync Duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(etcd_disk_wal_fsync_duration_seconds_bucket[1m])) by (instance, le))",
     "legendFormat": "{{instance}} WAL fsync"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(etcd_disk_backend_commit_duration_seconds_bucket[1m])) by (instance, le))",
     "legendFormat": "{{instance}} DB fsync"
    }
   ]
  },
  {
   "title": "Etcd DB Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 65 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "etcd_mvcc_db_total_size_in_bytes",
     "legendFormat": "{{instance}} DB Size"
    }
   ]
  },
  {
   "title": "Etcd slow applies per second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 73 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(etcd_server_slow_apply_total\n[1m])"
    }
   ]
  },
  {
   "title": "Wizard Bus Topics",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 73 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sensu_go_wizard_bus{topic=\"sensu:event-raw\",instance=\"10.0.42.15:8080\"}"
    },
    {
     "expr": "sensu_go_wizard_bus{topic=\"sensu:event\",instance=\"10.0.42.15:8080\"}"
    },
    {
     "expr": "sensu_go_wizard_bus{topic=\"sensu:keepalive\",instance=\"10.0.42.15:8080\"}"
    },
    {
     "expr": "sensu_go_wizard_bus{topic=\"sensu:check\",instance=\"10.0.42.15:8080\"}"
    },
    {
     "expr": "sensu_go_wizard_bus{topic=\"sensu:event-raw\",instance=\"10.0.42.16:8080\"}"
    },
    {
     "expr": "sensu_go_wizard_bus{topic=\"sensu:event\",instance=\"10.0.42.16:8080\"}"
    },
    {
     "expr": "sensu_go_wizard_bus{topic=\"sensu:keepalive\",instance=\"10.0.42.16:8080\"}"
    },
    {
     "expr": "sensu_go_wizard_bus{topic=\"sensu:check\",instance=\"10.0.42.16:8080\"}"
    },
    {
     "expr": "sensu_go_wizard_bus{topic=\"sensu:event-raw\",instance=\"10.0.42.17:8080\"}"
    },
    {
     "expr": "sensu_go_wizard_bus{topic=\"sensu:event\",instance=\"10.0.42.17:8080\"}"
    },
    {
     "expr": "sensu_go_wizard_bus{topic=\"sensu:keepalive\",instance=\"10.0.42.17:8080\"}"
    },
    {
     "expr": "sensu_go_wizard_bus{topic=\"sensu:check\",instance=\"10.0.42.17:8080\"}"
    }
   ]
  },
  { "title": "Version info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 81 } },
  {
   "title": "Sensu Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 82 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sensu_go_build_info" }
   ]
  },
  {
   "title": "Go Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 82 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sensu_go_build_info{instance=\"10.0.42.15:8080\"}"
    }
   ]
  },
  {
   "title": "Build SHA",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 82 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sensu_go_build_info" }
   ]
  },
  {
   "title": "Build Date",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 82 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sensu_go_build_info" }
   ]
  },
  { "title": "CPU/Mem", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 85 } },
  {
   "title": "CPU Basic",
   "type": "graph",
   "description": "Basic CPU info",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 86 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode=\"system\",instance=~\"$node:$port\",job=~\"$job\"}[5m])) * 100",
     "legendFormat": "Busy System"
    },
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode='user',instance=~\"$node:$port\",job=~\"$job\"}[5m])) * 100",
     "legendFormat": "Busy User"
    },
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode='iowait',instance=~\"$node:$port\",job=~\"$job\"}[5m])) * 100",
     "legendFormat": "Busy Iowait"
    },
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode=~\".*irq\",instance=~\"$node:$port\",job=~\"$job\"}[5m])) * 100",
     "legendFormat": "Busy IRQs"
    },
    {
     "expr": "sum (rate(node_cpu_seconds_total{mode!='idle',mode!='user',mode!='system',mode!='iowait',mode!='irq',mode!='softirq',instance=~\"$node:$port\",job=~\"$job\"}[5m])) * 100",
     "legendFormat": "Busy Other"
    },
    {
     "expr": "sum by (mode)(rate(node_cpu_seconds_total{mode='idle',instance=~\"$node:$port\",job=~\"$job\"}[5m])) * 100",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "title": "Memory Basic",
   "type": "graph",
   "description": "Basic memory usage",
   "gridPos": { "h": 7, "w": 7, "x": 9, "y": 86 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$node:$port\",job=~\"$job\"}",
     "legendFormat": "RAM Total"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$node:$port\",job=~\"$job\"} - node_memory_MemFree_bytes{instance=~\"$node:$port\",job=~\"$job\"} - (node_memory_Cached_bytes{instance=~\"$node:$port\",job=~\"$job\"} + node_memory_Buffers_bytes{instance=~\"$node:$port\",job=~\"$job\"})",
     "legendFormat": "RAM Used"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=~\"$node:$port\",job=~\"$job\"} + node_memory_Buffers_bytes{instance=~\"$node:$port\",job=~\"$job\"}",
     "legendFormat": "RAM Cache + Buffer"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=~\"$node:$port\",job=~\"$job\"}",
     "legendFormat": "RAM Free"
    },
    {
     "expr": "(node_memory_SwapTotal_bytes{instance=~\"$node:$port\",job=~\"$job\"} - node_memory_SwapFree_bytes{instance=~\"$node:$port\",job=~\"$job\"})",
     "legendFormat": "SWAP Used"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 86 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "process_resident_memory_bytes", "legendFormat": "{{instance}} Resident Memory" }
   ]
  },
  { "title": "Networking", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 93 } },
  {
   "title": "Client Traffic In",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 94 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(etcd_network_client_grpc_received_bytes_total[5m])",
     "legendFormat": "{{instance}} Client Traffic In"
    }
   ]
  },
  {
   "title": "Client Traffic Out",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 94 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(etcd_network_client_grpc_sent_bytes_total[5m])",
     "legendFormat": "{{instance}} Client Traffic Out"
    }
   ]
  },
  {
   "title": "Peer Traffic In",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 94 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(etcd_network_peer_received_bytes_total[5m])) by (instance)",
     "legendFormat": "{{instance}} Peer Traffic In"
    }
   ]
  },
  {
   "title": "Peer Traffic Out",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 94 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(etcd_network_peer_sent_bytes_total[5m])) by (instance)",
     "legendFormat": "{{instance}} Peer Traffic Out"
    }
   ]
  },
  {
   "title": "Network Traffic Basic",
   "type": "graph",
   "description": "Basic network info per interface",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 101 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{instance=~\"$node:$port\",job=~\"$job\"}[5m])",
     "legendFormat": "recv {{device}}"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{instance=~\"$node:$port\",job=~\"$job\"}[5m])",
     "legendFormat": "trans {{device}} "
    }
   ]
  },
  {
   "title": "RPC Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 101 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(grpc_server_started_total{grpc_type=\"unary\"}[5m]))",
     "legendFormat": "RPC Rate"
    },
    {
     "expr": "sum(rate(grpc_server_handled_total{grpc_type=\"unary\",grpc_code!=\"OK\"}[5m]))",
     "legendFormat": "RPC Failed Rate"
    }
   ]
  },
  { "title": "Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 108 } },
  {
   "title": "Disk IOps Completed",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 109 },
   "yaxes": [
    { "format": "iops", "label": "IO read (-) / write (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_reads_completed_total{instance=~\"$node:$port\",job=~\"$job\"}[1m])",
     "legendFormat": "{{device}} - Reads completed"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{instance=~\"$node:$port\",job=~\"$job\"}[1m])",
     "legendFormat": "{{device}} - Writes completed"
    }
   ]
  },
  {
   "title": "Disk R/W Data",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 109 },
   "yaxes": [
    { "format": "Bps", "label": "Bytes read (-) / write (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total{instance=~\"$node:$port\",job=~\"$job\"}[5m])",
     "legendFormat": "{{device}} - Read bytes"
    },
    {
     "expr": "irate(node_disk_written_bytes_total{instance=~\"$node:$port\",job=~\"$job\"}[5m])",
     "legendFormat": "{{device}} - Written bytes"
    }
   ]
  }
 ]
}